### ISSUE TITLE
Doest not count elixirs and potions on Shadow Priest

### ISSUE THREAD

**Issue by sturhm-gif** [Otari98/BetterCharacterStats#32]
Pretty much title, looking at spell power it does not count anything over 440 on my Shadow Priest. I think I had the same issue on my Shaman as well.

I have not tried or tested with food buffs, but I suspect its the same issue

**Comment by Otari98** [comment]
proofs? any speciffic items/buffs/enchants?

**Comment by Otari98** [comment]
fixed 1cc1f304e788c229629444ced414eb4904dab7a5

**Comment by sturhm-gif** [comment]
I redownloaded, but still doesnt count with elixir of shadow power on my char. Do i have to do something else to have it work ?

**Comment by sturhm-gif** [comment]
It is this one

https://www.wowhead.com/classic/item=9264/elixir-of-shadow-power

**Comment by Otari98** [comment]
https://youtu.be/CjnltLgCT_c

its works for me

**Comment by sturhm-gif** [comment]
Not for me still

https://youtu.be/GAWgzat0db4
